"""Multi-system cognition core (habit / control / memory) for L.I.F.E."""

from .model import (
    CognitionConfig,
    Decision,
    Engram,
    MODE_MODULES,
    MODE_ORDER,
    MultiSystemModel,
    ToyTask,
)
from .circuits import (
    CIRCUITS,
    COMMUNICATIVE_FUNCTIONS,
    FLEXIBILITY_PROFILES,
    SOCIAL_BASIS,
    CerebellarPredictor,
    CogLinksArbiter,
    DistributedEvidence,
    DistributedReadout,
    Flexibility,
    GlobalWorkspace,
    GroupCoupling,
    Ignition,
    Metacognition,
    OFCValueMap,
    Prospection,
    SelfModel,
    SocialCoder,
    SocialReading,
    hebbian_gate,
)
from .space import (
    ACTION_GUIDANCE,
    CognitionEngine,
    ControlOutcome,
    LIFE_ACTIONS,
    N_FEATURES,
    N_STATES,
    context_factors,
    context_features,
    reward_from_signals,
    state_index,
)
from .affect import (
    ERQ_PROFILES,
    AffectConfig,
    AffectSystem,
    ArousalGain,
    AttachmentTemplate,
    BeliefBehaviorMonitor,
    DepressiveEpisode,
    DesireSystem,
    EmotionRegulator,
    HPAxis,
    InteroceptiveChannel,
    MoodAttractor,
    NeuroImmune,
    PADState,
    PrecisionController,
    RewardAvailability,
    ThreatBias,
    VagalTone,
)
from .somatic import (
    SYMPTOM_CHANNELS,
    SomaticSymptomSystem,
)
from .persona_traits import (
    PERSONA_JSON_CONTRACT,
    PersonaTraits,
    merge_persona_llm_json,
    parse_persona,
    persona_summary,
    refine_persona_with_llm,
)
from .language import (
    FRAMING_MODES,
    LanguageConfig,
    LanguageSystem,
    LinguisticFraming,
    StructuralLearner,
    WordSegmenter,
    tokenize,
)
from .social import (
    SELMAN_STAGES,
    IntrinsicMotivation,
    PerspectiveTaking,
    ProsocialAlignment,
    RoleModelLearning,
    SocialConfig,
    SocialLearning,
    SocialSystem,
    SocialTies,
)
from .selfhood import (
    ATTENTION_STATES,
    AffectivePrimacy,
    CognitiveLoad,
    MetaAwareness,
    NarrativeIdentity,
    PersonaDetail,
    SelfhoodConfig,
    SelfhoodSystem,
    TemporalDiscounting,
)
from .relating import (
    AXES,
    RepairModel,
    RelatingSystem,
    TraitModel,
    signals_from_message,
)
from .attachment import (
    ACTIONS as ATTACHMENT_ACTIONS,
    AttachmentDynamics,
    AttachmentSystem,
    TYPES as ATTACHMENT_TYPES,
    initial_state_for_persona,
    severity_band as attachment_severity_band,
    type_for_persona as attachment_type_for_persona,
)
from .persona_style import (
    CHARACTER_TYPES,
    RELATIONSHIP_TYPES,
    character_options,
    classify_character,
    classify_relationship,
    relationship_attachment_type,
    relationship_is_pathological,
    relationship_options,
)

__all__ = [
    "ACTION_GUIDANCE",
    "CIRCUITS",
    "COMMUNICATIVE_FUNCTIONS",
    "CerebellarPredictor",
    "CognitionConfig",
    "CognitionEngine",
    "CogLinksArbiter",
    "ControlOutcome",
    "Decision",
    "DistributedEvidence",
    "DistributedReadout",
    "Engram",
    "FLEXIBILITY_PROFILES",
    "Flexibility",
    "GlobalWorkspace",
    "GroupCoupling",
    "Ignition",
    "LIFE_ACTIONS",
    "MODE_MODULES",
    "MODE_ORDER",
    "Metacognition",
    "MultiSystemModel",
    "N_FEATURES",
    "N_STATES",
    "OFCValueMap",
    "Prospection",
    "SOCIAL_BASIS",
    "SelfModel",
    "SocialCoder",
    "SocialReading",
    "ToyTask",
    "context_factors",
    "context_features",
    "hebbian_gate",
    "reward_from_signals",
    "state_index",
    # --- second wave: affective / interoceptive / clinical circuits ---
    "ERQ_PROFILES",
    "AffectConfig",
    "AffectSystem",
    "ArousalGain",
    "AttachmentTemplate",
    "BeliefBehaviorMonitor",
    "DepressiveEpisode",
    "DesireSystem",
    "EmotionRegulator",
    "HPAxis",
    "InteroceptiveChannel",
    "MoodAttractor",
    "NeuroImmune",
    "PADState",
    "PrecisionController",
    "RewardAvailability",
    "ThreatBias",
    "VagalTone",
    # --- somatization: the psychological -> bodily gateway ---
    "SYMPTOM_CHANNELS",
    "SomaticSymptomSystem",
    # --- persona -> trait parameters (人设 → 模型数据) ---
    "PERSONA_JSON_CONTRACT",
    "PersonaTraits",
    "merge_persona_llm_json",
    "parse_persona",
    "persona_summary",
    "refine_persona_with_llm",
    # --- persona style: character archetypes + relationship styles ---
    "CHARACTER_TYPES",
    "RELATIONSHIP_TYPES",
    "character_options",
    "classify_character",
    "classify_relationship",
    "relationship_attachment_type",
    "relationship_is_pathological",
    "relationship_options",
    # --- third wave: language acquisition + the language-thought interface ---
    "FRAMING_MODES",
    "LanguageConfig",
    "LanguageSystem",
    "LinguisticFraming",
    "StructuralLearner",
    "WordSegmenter",
    "tokenize",
    # --- fourth wave: social learning / ties / prosocial alignment ---
    "SELMAN_STAGES",
    "IntrinsicMotivation",
    "PerspectiveTaking",
    "ProsocialAlignment",
    "RoleModelLearning",
    "SocialConfig",
    "SocialLearning",
    "SocialSystem",
    "SocialTies",
    # --- fourth wave: selfhood, time, load and metacognition ---
    "ATTENTION_STATES",
    "AffectivePrimacy",
    "CognitiveLoad",
    "MetaAwareness",
    "NarrativeIdentity",
    "PersonaDetail",
    "SelfhoodConfig",
    "SelfhoodSystem",
    "TemporalDiscounting",
    # --- reciprocity: shared trait space + rupture/repair ---
    "AXES",
    "RepairModel",
    "RelatingSystem",
    "TraitModel",
    "signals_from_message",
    # --- pathological attachment (the "yandere" model) ---
    "ATTACHMENT_ACTIONS",
    "ATTACHMENT_TYPES",
    "AttachmentDynamics",
    "AttachmentSystem",
    "attachment_severity_band",
    "attachment_type_for_persona",
    "initial_state_for_persona",
]
