"""Multi-system cognition core (habit / control / memory) for L.I.F.E."""

from .model import (
    CognitionConfig,
    Decision,
    Engram,
    MODE_MODULES,
    MODE_ORDER,
    MultiSystemModel,
    ToyTask,
)
from .circuits import (
    CIRCUITS,
    COMMUNICATIVE_FUNCTIONS,
    FLEXIBILITY_PROFILES,
    SOCIAL_BASIS,
    CerebellarPredictor,
    CogLinksArbiter,
    DistributedEvidence,
    DistributedReadout,
    Flexibility,
    GlobalWorkspace,
    GroupCoupling,
    Ignition,
    Metacognition,
    OFCValueMap,
    Prospection,
    SelfModel,
    SocialCoder,
    SocialReading,
    hebbian_gate,
)
from .space import (
    ACTION_GUIDANCE,
    CognitionEngine,
    ControlOutcome,
    LIFE_ACTIONS,
    N_FEATURES,
    N_STATES,
    context_factors,
    context_features,
    reward_from_signals,
    state_index,
)
from .affect import (
    ERQ_PROFILES,
    AffectConfig,
    AffectSystem,
    ArousalGain,
    AttachmentTemplate,
    BeliefBehaviorMonitor,
    DepressiveEpisode,
    DesireSystem,
    EmotionRegulator,
    HPAxis,
    InteroceptiveChannel,
    MoodAttractor,
    NeuroImmune,
    PADState,
    PrecisionController,
    RewardAvailability,
    ThreatBias,
    VagalTone,
)
from .somatic import (
    SYMPTOM_CHANNELS,
    SomaticSymptomSystem,
)
from .persona_traits import (
    GENDERS,
    PERSONA_JSON_CONTRACT,
    PersonaTraits,
    detect_gender,
    merge_persona_llm_json,
    parse_persona,
    persona_summary,
    refine_persona_with_llm,
)
from .language import (
    FRAMING_MODES,
    LanguageConfig,
    LanguageSystem,
    LinguisticFraming,
    StructuralLearner,
    WordSegmenter,
    tokenize,
)
from .social import (
    SELMAN_STAGES,
    IntrinsicMotivation,
    PerspectiveTaking,
    ProsocialAlignment,
    RoleModelLearning,
    SocialConfig,
    SocialLearning,
    SocialSystem,
    SocialTies,
)
from .selfhood import (
    ATTENTION_STATES,
    AffectivePrimacy,
    CognitiveLoad,
    MetaAwareness,
    NarrativeIdentity,
    PersonaDetail,
    SelfhoodConfig,
    SelfhoodSystem,
    TemporalDiscounting,
)
from .relating import (
    AXES,
    RepairModel,
    RelatingSystem,
    TraitModel,
    signals_from_message,
)
from .attachment import (
    ACTIONS as ATTACHMENT_ACTIONS,
    AttachmentDynamics,
    AttachmentSystem,
    TYPES as ATTACHMENT_TYPES,
    initial_state_for_persona,
    severity_band as attachment_severity_band,
    type_for_persona as attachment_type_for_persona,
)
from .tsundere import (
    BANDS as TSUNDERE_BANDS,
    TsundereDynamics,
    TsundereSystem,
    TYPES as TSUNDERE_TYPES,
    initial_state_for_persona as tsundere_initial_state_for_persona,
    regime as tsundere_regime,
    type_for_persona as tsundere_type_for_persona,
)
from .common import (
    SAFETY_GUARD,
    clamp,
    clamp01,
    clamp_signed,
    emotion_label,
    match_persona_hints,
    safety_guard,
)
from .yandere import (
    EVENT_EFFECTS as YANDERE_EVENTS,
    MODES as YANDERE_MODES,
    TYPES as YANDERE_TYPES,
    BigFive,
    DereProfile,
    Event,
    YANDERE_SIGNATURE,
    YandereDynamics,
    YandereSystem,
    emotion_label as yandere_emotion_label,
    initial_state_for_persona as yandere_initial_state_for_persona,
    traits_to_profile,
    type_for_persona as yandere_type_for_persona,
    yandere_signature_score,
)
from .persona_dynamics import (
    ACTIONS as PERSONA_ACTIONS,
    ACTION_LAYERS as PERSONA_ACTION_LAYERS,
    ALL_ACTIONS as PERSONA_ALL_ACTIONS,
    DES as PERSONA_DES,
    DES16 as PERSONA_DES16,
    DESIRE_GROUPS as PERSONA_DESIRE_GROUPS,
    EMO as PERSONA_EMO,
    EMO16 as PERSONA_EMO16,
    EMOTION_GROUPS as PERSONA_EMOTION_GROUPS,
    GENDER_SCRIPTS as PERSONA_GENDER_SCRIPTS,
    THETA_GROUPS as PERSONA_THETA_GROUPS,
    THETA_DIM as PERSONA_THETA_DIM,
    TYPE_ROWS as PERSONA_TYPE_ROWS,
    PersonaDynamics,
    PersonaDynamicsSystem,
    THRESH as PERSONA_THRESH,
    TYPES as PERSONA_TYPES,
    GenderScript,
    derive_big5 as persona_dynamics_derive_big5,
    derive_disc as persona_dynamics_derive_disc,
    derive_hexaco as persona_dynamics_derive_hexaco,
    derive_mbti as persona_dynamics_derive_mbti,
    gender_for_persona as persona_dynamics_gender_for_persona,
    initial_state_for_persona as persona_dynamics_initial_state_for_persona,
    is_deployable as persona_dynamics_is_deployable,
    type_for_persona as persona_dynamics_type_for_persona,
    type_probabilities as persona_dynamics_type_probabilities,
)
from .persona_style import (
    CHARACTER_TYPES,
    RELATIONSHIP_TYPES,
    character_options,
    character_spec,
    classify_character,
    classify_relationship,
    relationship_attachment_type,
    relationship_is_pathological,
    relationship_options,
    relationship_spec,
)

__all__ = [
    "ACTION_GUIDANCE",
    "CIRCUITS",
    "COMMUNICATIVE_FUNCTIONS",
    "CerebellarPredictor",
    "CognitionConfig",
    "CognitionEngine",
    "CogLinksArbiter",
    "ControlOutcome",
    "Decision",
    "DistributedEvidence",
    "DistributedReadout",
    "Engram",
    "FLEXIBILITY_PROFILES",
    "Flexibility",
    "GlobalWorkspace",
    "GroupCoupling",
    "Ignition",
    "LIFE_ACTIONS",
    "MODE_MODULES",
    "MODE_ORDER",
    "Metacognition",
    "MultiSystemModel",
    "N_FEATURES",
    "N_STATES",
    "OFCValueMap",
    "Prospection",
    "SOCIAL_BASIS",
    "SelfModel",
    "SocialCoder",
    "SocialReading",
    "ToyTask",
    "context_factors",
    "context_features",
    "hebbian_gate",
    "reward_from_signals",
    "state_index",
    # --- second wave: affective / interoceptive / clinical circuits ---
    "ERQ_PROFILES",
    "AffectConfig",
    "AffectSystem",
    "ArousalGain",
    "AttachmentTemplate",
    "BeliefBehaviorMonitor",
    "DepressiveEpisode",
    "DesireSystem",
    "EmotionRegulator",
    "HPAxis",
    "InteroceptiveChannel",
    "MoodAttractor",
    "NeuroImmune",
    "PADState",
    "PrecisionController",
    "RewardAvailability",
    "ThreatBias",
    "VagalTone",
    # --- somatization: the psychological -> bodily gateway ---
    "SYMPTOM_CHANNELS",
    "SomaticSymptomSystem",
    # --- persona -> trait parameters (人设 → 模型数据) ---
    "GENDERS",
    "PERSONA_JSON_CONTRACT",
    "PersonaTraits",
    "detect_gender",
    "merge_persona_llm_json",
    "parse_persona",
    "persona_summary",
    "refine_persona_with_llm",
    # --- persona style: character archetypes + relationship styles ---
    "CHARACTER_TYPES",
    "RELATIONSHIP_TYPES",
    "character_options",
    "character_spec",
    "classify_character",
    "classify_relationship",
    "relationship_attachment_type",
    "relationship_is_pathological",
    "relationship_options",
    "relationship_spec",
    # --- third wave: language acquisition + the language-thought interface ---
    "FRAMING_MODES",
    "LanguageConfig",
    "LanguageSystem",
    "LinguisticFraming",
    "StructuralLearner",
    "WordSegmenter",
    "tokenize",
    # --- fourth wave: social learning / ties / prosocial alignment ---
    "SELMAN_STAGES",
    "IntrinsicMotivation",
    "PerspectiveTaking",
    "ProsocialAlignment",
    "RoleModelLearning",
    "SocialConfig",
    "SocialLearning",
    "SocialSystem",
    "SocialTies",
    # --- fourth wave: selfhood, time, load and metacognition ---
    "ATTENTION_STATES",
    "AffectivePrimacy",
    "CognitiveLoad",
    "MetaAwareness",
    "NarrativeIdentity",
    "PersonaDetail",
    "SelfhoodConfig",
    "SelfhoodSystem",
    "TemporalDiscounting",
    # --- reciprocity: shared trait space + rupture/repair ---
    "AXES",
    "RepairModel",
    "RelatingSystem",
    "TraitModel",
    "signals_from_message",
    # --- pathological attachment (the "yandere" model) ---
    "ATTACHMENT_ACTIONS",
    "ATTACHMENT_TYPES",
    "AttachmentDynamics",
    "AttachmentSystem",
    "attachment_severity_band",
    "attachment_type_for_persona",
    "initial_state_for_persona",
    # --- tsundere <-> yandere emotional dynamics ---
    "TSUNDERE_BANDS",
    "TSUNDERE_TYPES",
    "TsundereDynamics",
    "TsundereSystem",
    "tsundere_initial_state_for_persona",
    "tsundere_regime",
    "tsundere_type_for_persona",
    # --- yandere affect dynamics (柳・米澤 2023: circumplex + C1/C2/C3) ---
    "YANDERE_EVENTS",
    "YANDERE_MODES",
    "YANDERE_SIGNATURE",
    "YANDERE_TYPES",
    "BigFive",
    "DereProfile",
    "Event",
    "YandereDynamics",
    "YandereSystem",
    "traits_to_profile",
    "yandere_emotion_label",
    "yandere_initial_state_for_persona",
    "yandere_signature_score",
    "yandere_type_for_persona",
    # --- parameterised persona dynamics (θ / D / x / f / g / T / G / L) ---
    "PERSONA_ACTIONS",
    "PERSONA_ACTION_LAYERS",
    "PERSONA_ALL_ACTIONS",
    "PERSONA_DES",
    "PERSONA_DES16",
    "PERSONA_DESIRE_GROUPS",
    "PERSONA_EMO",
    "PERSONA_EMO16",
    "PERSONA_EMOTION_GROUPS",
    "PERSONA_GENDER_SCRIPTS",
    "PERSONA_THETA_GROUPS",
    "PERSONA_THETA_DIM",
    "PERSONA_TYPE_ROWS",
    "PERSONA_THRESH",
    "PERSONA_TYPES",
    "GenderScript",
    "PersonaDynamics",
    "PersonaDynamicsSystem",
    "persona_dynamics_derive_big5",
    "persona_dynamics_derive_disc",
    "persona_dynamics_derive_hexaco",
    "persona_dynamics_derive_mbti",
    "persona_dynamics_gender_for_persona",
    "persona_dynamics_initial_state_for_persona",
    "persona_dynamics_is_deployable",
    "persona_dynamics_type_for_persona",
    "persona_dynamics_type_probabilities",
]
