<script setup lang="ts">
import {ref,computed,onMounted,onUnmounted,watch,nextTick} from 'vue'
import {useI18n} from 'vue-i18n'
const {locale}=useI18n();const en=computed(()=>locale.value==='en')
const items=ref<any[]>([]),answer=ref(''),error=ref(''),sending=ref(false),collapsed=ref(false)
const current=computed(()=>items.value[0]);let timer:ReturnType<typeof setInterval>|undefined;let fetching=false
const dialog=ref<HTMLElement|null>(null);let previousFocus:HTMLElement|null=null
watch(()=>!!current.value&&!collapsed.value,async open=>{if(open){previousFocus=document.activeElement as HTMLElement;await nextTick();dialog.value=document.querySelector('.inbox-dialog');if(dialog.value){dialog.value.tabIndex=-1;dialog.value.focus()}}else{dialog.value=null;previousFocus?.focus()}})
function trap(event:KeyboardEvent){if(event.key!=='Tab')return;const focusable=[...dialog.value?.querySelectorAll<HTMLElement>('button:not(:disabled),textarea:not(:disabled)')||[]];if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&(document.activeElement===first||document.activeElement===dialog.value)){event.preventDefault();last.focus()}else if(!event.shiftKey&&(document.activeElement===last||document.activeElement===dialog.value)){event.preventDefault();first.focus()}}
async function poll(){if(fetching)return;fetching=true;try{const response=await fetch('/api/agent/inbox',{signal:AbortSignal.timeout(8000)});if(!response.ok)throw new Error(await response.text());const data=await response.json();items.value=[...(data.approvals||[]).map((item:any)=>({...item,kind:'approvals'})),...(data.questions||[]).map((item:any)=>({...item,kind:'questions'}))].sort((a,b)=>String(a.created_at||'').localeCompare(String(b.created_at||''))||String(a.id||'').localeCompare(String(b.id||'')))}catch{/* keep pending requests during reconnect */}finally{fetching=false}}
watch(()=>current.value?.id,()=>{answer.value='';error.value='';collapsed.value=false})
async function respond(allow?:boolean){if(!current.value||sending.value)return;sending.value=true;try{const item=current.value;const response=await fetch(`/api/agent/${item.kind}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id,executor_id:item.executor_id,...(item.kind==='questions'?{answer:answer.value}:{allow})})});if(!response.ok)throw new Error(await response.text());items.value=items.value.filter(value=>value.id!==item.id);await poll()}catch(e:any){error.value=e.message}finally{sending.value=false}}
onMounted(()=>{poll();timer=setInterval(poll,1500);document.addEventListener('keydown',trap)});onUnmounted(()=>{clearInterval(timer);document.removeEventListener('keydown',trap)})
</script>
<template><Teleport to="body"><button v-if="current&&collapsed" class="inbox-fab" @click="collapsed=false">{{ en?'Agent needs you':'Agent 等待处理' }} · {{ items.length }}</button><div v-if="current&&!collapsed" class="inbox-scrim"><section class="inbox-dialog" role="dialog" aria-modal="true" :aria-label="en?'Agent interaction':'Agent 交互'" @keydown.esc="collapsed=true"><header><div><span class="inbox-eyebrow">AGENT · {{ items.length }}</span><h2>{{ current.kind==='questions'?(en?'A question for you':'Agent 想问你'):(en?'Permission required':'需要你的许可') }}</h2></div><button @click="collapsed=true">{{ en?'Later':'稍后' }}</button></header><p class="inbox-meta">{{ current.executor_id }} · {{ current.session_id }}</p><template v-if="current.kind==='questions'"><h3>{{ current.question }}</h3><div class="inbox-choices"><button v-for="option in current.options" :key="option" :class="{chosen:answer===option}" @click="answer=option">{{ option }}</button></div><textarea v-model="answer" :placeholder="en?'Or write your own response…':'也可以自己填写回复…'" /><footer><button class="inbox-primary" :disabled="sending||!answer.trim()" @click="respond()">{{ en?'Send answer':'发送回复' }}</button></footer></template><template v-else><h3>{{ current.tool }}</h3><p>{{ current.cwd }}</p><pre>{{ JSON.stringify(current.args,null,2) }}</pre><footer><button :disabled="sending" @click="respond(false)">{{ en?'Deny':'拒绝' }}</button><button class="inbox-primary" :disabled="sending" @click="respond(true)">{{ en?'Allow this time':'允许本次执行' }}</button></footer></template><p v-if="error" role="alert">{{ error }}</p></section></div></Teleport></template>
<style>
.inbox-scrim{position:fixed;inset:0;z-index:12000;background:#18132d66;backdrop-filter:blur(6px);display:grid;place-items:center;padding:20px}.inbox-dialog{width:min(560px,100%);max-height:85vh;overflow:auto;border-radius:28px;background:var(--md-surface);color:var(--md-on-surface);padding:28px;box-shadow:0 24px 70px #18132d33;animation:dialog-arrive 280ms var(--ease-emphasized)}.inbox-dialog header{display:flex;justify-content:space-between;align-items:center;gap:16px}.inbox-eyebrow{font-size:12px;letter-spacing:2px;color:var(--md-primary);font-weight:700}.inbox-dialog h2{font-size:24px;margin:8px 0}.inbox-dialog h3{font-size:17px;margin:18px 0 10px}.inbox-meta{font-size:12px;color:var(--md-on-surface-variant);overflow-wrap:anywhere}.inbox-dialog pre{white-space:pre-wrap;overflow-wrap:anywhere;background:var(--md-surface-container);border-radius:16px;padding:16px;max-height:240px;overflow:auto;margin:16px 0}.inbox-dialog button,.inbox-fab{border:0;border-radius:999px;padding:12px 20px;font:inherit;cursor:pointer;background:var(--md-secondary-container);color:var(--md-on-secondary-container)}.inbox-dialog button:disabled{opacity:.4}.inbox-dialog .inbox-primary,.inbox-fab{background:var(--md-primary);color:var(--md-on-primary)}.inbox-dialog footer{display:flex;justify-content:flex-end;gap:12px;margin-top:20px}.inbox-choices{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}.inbox-choices .chosen{background:var(--md-primary-container);outline:2px solid var(--md-primary)}.inbox-dialog textarea{width:100%;min-height:90px;padding:12px;border-radius:16px;border:1px solid var(--md-outline-variant);background:var(--md-surface-container-low);font:inherit}.inbox-fab{position:fixed;right:24px;bottom:24px;z-index:12000;box-shadow:var(--shadow-3)}
</style>
