<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
const data = ref<any>({ relationships:[], agenda:[], journal:[], dreams:[], audit:[], groups:{}, proactive:{} })
const loading = ref(false); const error = ref(''); const agendaTitle = ref(''); const agendaWhen = ref(''); const agendaDetail = ref(''); const journal = ref(''); const dream = ref('')
const groups = computed(() => Object.entries(data.value.groups || {}))
async function load(){loading.value=true;error.value='';try{const r=await fetch('/api/life/companion');if(!r.ok)throw Error(String(r.status));data.value=await r.json()}catch(e:any){error.value=e?.message||'无法读取 LIFE 陪伴状态'}finally{loading.value=false}}
async function act(action:string,payload:any){try{const r=await fetch('/api/life/companion',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,payload})});if(!r.ok)throw Error(await r.text());await load()}catch(e:any){error.value=e?.message||'操作失败'}}
async function addAgenda(){if(!agendaTitle.value.trim())return;await act('add_agenda',{title:agendaTitle.value,when:agendaWhen.value,detail:agendaDetail.value});agendaTitle.value='';agendaWhen.value='';agendaDetail.value=''}
async function addEntry(kind:'journal'|'dream',content:string){if(!content.trim())return;await act(kind,{content});if(kind==='journal')journal.value='';else dream.value=''}
onMounted(load)
</script>
<template><main class="page"><header><div><p>L.I.F.E / COMPANION</p><h1>陪伴面板</h1><span>日程、关系、生活状态、梦境、日记、群聊观察和主动行为审计均由 LIFE 插件维护。</span></div><button @click="load">{{loading?'刷新中…':'刷新'}}</button></header><p v-if="error" class="error">{{error}}</p>
<section class="stats"><article><b>{{data.relationships?.length||0}}</b><span>关系对象</span></article><article><b>{{data.agenda?.filter((x:any)=>x.status==='active').length||0}}</b><span>活动日程</span></article><article><b>{{data.proactive?.candidates?.filter((x:any)=>x.status==='delivered').length||0}}</b><span>已投递主动行为</span></article><article><b>{{groups.length}}</b><span>已观察群聊</span></article></section>
<section class="grid"><article><h2>日程</h2><div class="form"><input v-model="agendaTitle" placeholder="日程标题"/><input v-model="agendaWhen" placeholder="时间，例如 2026-09-25 20:00"/><textarea v-model="agendaDetail" placeholder="说明（可选）"/><button @click="addAgenda">创建候选</button></div><h3>待确认候选</h3><ul><li v-for="item in data.calendar_candidates?.filter((x:any)=>x.status==='pending_confirmation')" :key="item.id"><strong>{{item.title}}</strong><small>{{item.when_text}} {{item.detail}}</small><button @click="act('confirm_agenda',{id:item.id})">确认</button><button class="reject" @click="act('reject_agenda',{id:item.id})">拒绝</button></li></ul><h3>已确认日程</h3><ul><li v-for="item in data.agenda" :key="item.id"><label><input :checked="item.status==='completed'" type="checkbox" @change="act('complete_agenda',{id:item.id})"/><span :class="{done:item.status==='completed'}">{{item.title}}</span></label><small>{{item.start_at}} {{item.detail}}</small></li></ul></article>
<article><h2>关系账本</h2><div class="relations"><div v-for="rel in data.relationships" :key="rel.user_id"><strong>{{rel.user_id}}</strong><span>{{rel.stage}} · 好感 {{Math.round((rel.affinity||0)*100)}}%</span><small>最近互动：{{rel.last_seen||'暂无'}}</small></div><p v-if="!data.relationships?.length">暂无关系记录</p></div></article>
<article><h2>成长中的性格</h2><div class="relations"><div v-for="trait in data.persona_evolution" :key="trait.id"><strong>{{trait.trait}}</strong><span>{{trait.value}}</span><small>支持 {{trait.support_count}} 次 · 置信度 {{Math.round(trait.confidence*100)}}%</small></div><p v-if="!data.persona_evolution?.length">LIFE 还在观察，重复出现的稳定倾向才会被确认。</p></div></article>
<article><h2>日记</h2><textarea v-model="journal" placeholder="记录 LIFE 的日记…"/><button @click="addEntry('journal',journal)">写入日记</button><ol><li v-for="item in data.journal" :key="item.id"><small>{{item.at}}</small><p>{{item.content}}</p></li></ol></article>
<article><h2>梦境</h2><textarea v-model="dream" placeholder="记录一个梦境或睡眠反思…"/><button @click="addEntry('dream',dream)">记录梦境</button><ol><li v-for="item in data.dreams" :key="item.id"><small>{{item.at}}</small><p>{{item.content}}</p></li></ol></article>
<article><h2>群聊观察</h2><div v-for="[id,group] in groups" :key="id" class="group"><strong>{{id}}</strong><small>{{(group as any).messages?.length||0}} 条观察 · {{Object.keys((group as any).members||{}).length}} 位成员</small></div><p v-if="!groups.length">群聊观察尚未启用或没有消息。</p></article>
<article><h2>审计</h2><ol class="audit"><li v-for="item in data.audit" :key="item.at+item.kind"><strong>{{item.kind}}</strong><small>{{item.at}} · {{item.target}} · {{item.outcome}}</small><p>{{item.detail}}</p></li></ol><button @click="act('memory_maintenance',{})">执行记忆维护与备份</button></article></section></main></template>
<style scoped>.page{height:100%;overflow:auto;padding:30px;background:var(--md-surface)}header{max-width:1240px;margin:auto;display:flex;justify-content:space-between;gap:20px}header p{margin:0;color:var(--md-primary);font:700 12px monospace;letter-spacing:.1em}h1{margin:8px 0}header span,small{color:var(--md-on-surface-variant)}button{border:0;border-radius:999px;background:var(--md-primary);color:var(--md-on-primary);padding:10px 16px;cursor:pointer;height:max-content}.reject{background:var(--md-error);margin-left:6px}.stats,.grid{max-width:1240px;margin:24px auto;display:grid;gap:14px}.stats{grid-template-columns:repeat(4,1fr)}.stats article,.grid article{background:var(--md-surface-container-low);border:1px solid var(--md-outline-variant);border-radius:16px;padding:18px}.stats b{font-size:30px;display:block}.stats span{font-size:13px;color:var(--md-on-surface-variant)}.grid{grid-template-columns:repeat(2,minmax(0,1fr))}h2{margin:0 0 14px;font-size:17px}h3{margin:18px 0 4px;font-size:13px;color:var(--md-on-surface-variant)}input,textarea{box-sizing:border-box;width:100%;margin:5px 0;padding:9px;border:1px solid var(--md-outline-variant);border-radius:8px;background:var(--md-surface-container-lowest);color:var(--md-on-surface)}textarea{min-height:74px;resize:vertical}.form button,article>button{margin-top:8px}ul,ol{padding-left:18px;max-height:260px;overflow:auto}li{margin:10px 0}li small{display:block;margin-top:3px}.done{text-decoration:line-through;color:var(--md-on-surface-variant)}.relations>div,.group{padding:10px 0;border-bottom:1px solid var(--md-outline-variant)}.relations span,.relations small,.group small{display:block;margin-top:3px}.audit p,ol p{white-space:pre-wrap;margin:4px 0}.error{max-width:1240px;margin:12px auto;color:var(--md-error)}@media(max-width:800px){.page{padding:18px}.stats,.grid{grid-template-columns:1fr 1fr}.grid{grid-template-columns:1fr}header{display:block}header button{margin-top:12px}}</style>
