"""Procedural city map for a fictional world.

The road network is generated by **recursive subdivision** (a Parish-style city
generator): a land area is repeatedly split by streets — the first, longest cuts
become arterials, later cuts become local streets — and every leaf polygon is a
city block. Regular rectangular buildings and named compounds (小区) are placed
inside the blocks, and the model names the roads, metro lines/stations, bus
routes/stops, parks, water, districts, compounds and cities.

Everything is deterministic from (country, city), so the same setting always
yields the same map. The model's *raw input* is what gets persisted (not the
built geometry), so the map is warped exactly once per build. Rendered by
Leaflet on a simple CRS, so it pans and zooms like a real map.
"""
from __future__ import annotations

import hashlib
import math
import random
import re

WIDTH = 1000
HEIGHT = 700
_DEFAULT_DISTRICTS = ["老城区", "新城区", "东区", "西区", "南区", "北区", "城郊", "港区"]
_METRO_COLORS = ["#d64545", "#2e6fd6", "#2f9e6b", "#8b5cd6"]
_BUS_COLORS = ["#e08a2e", "#3aa0a2", "#b5567c", "#5b8def"]
_COLOR_RE = re.compile(r"^#[0-9a-fA-F]{3,6}$")
_ROAD_KINDS = ("major", "arterial", "street")
# A city reads as a city, not a dish-drain: bigger blocks, real open space.
_MIN_BLOCK_AREA = 11500.0
_ROAD_PREFIX = ["人民", "解放", "建设", "和平", "新华", "文化", "朝阳", "滨江", "青云", "中山",
                "光明", "胜利", "凯旋", "长虹", "望海", "临江", "白鹭", "梧桐", "银杏", "荷塘",
                "月湖", "南山", "东环", "西城", "春晓", "秋实", "和风", "清川"]
_ROAD_SUFFIX = ["路", "街", "大道"]
_BUILDING_PREFIX = ["星月", "龙井", "晨光", "云栖", "海风", "临江", "望湖", "青川", "梧桐", "白鹭",
                    "南山", "春晓", "金桂", "银杏", "广厦", "汇景", "滨江", "银河", "锦绣"]
_BUILDING_SUFFIX = ["大厦", "公寓", "中心", "写字楼", "花园", "广场", "苑", "阁", "公馆", "大厦"]
_COMPOUND_SUFFIX = ["小区", "家园", "花园", "苑", "新村", "公寓区"]


def _seed(text: str) -> int:
    return int(hashlib.md5(str(text or "world").encode("utf-8")).hexdigest()[:8], 16)


def _float(value, default: float) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def _clamp(value: float, low: float, high: float) -> float:
    return max(low, min(high, value))


# --------------------------------------------------------------------- geometry
def _area(poly) -> float:
    total = 0.0
    for i in range(len(poly)):
        x1, y1 = poly[i]
        x2, y2 = poly[(i + 1) % len(poly)]
        total += x1 * y2 - x2 * y1
    return abs(total) / 2.0


def _centroid(poly) -> list[float]:
    a = cx = cy = 0.0
    for i in range(len(poly)):
        x1, y1 = poly[i]
        x2, y2 = poly[(i + 1) % len(poly)]
        cross = x1 * y2 - x2 * y1
        a += cross
        cx += (x1 + x2) * cross
        cy += (y1 + y2) * cross
    if abs(a) < 1e-9:
        return [sum(p[0] for p in poly) / len(poly), sum(p[1] for p in poly) / len(poly)]
    return [cx / (3 * a), cy / (3 * a)]


def _side(p, a, b) -> float:
    return (b[0] - a[0]) * (p[1] - a[1]) - (b[1] - a[1]) * (p[0] - a[0])


def _clip(poly, a, b, keep_left):
    out = []
    n = len(poly)
    for i in range(n):
        p, q = poly[i], poly[(i + 1) % n]
        sp, sq = _side(p, a, b), _side(q, a, b)
        pin = sp >= 0 if keep_left else sp <= 0
        qin = sq >= 0 if keep_left else sq <= 0
        if pin:
            out.append(p)
        if pin != qin and (sp - sq) != 0:
            t = sp / (sp - sq)
            out.append([p[0] + (q[0] - p[0]) * t, p[1] + (q[1] - p[1]) * t])
    return out


def _cut(poly, a, b):
    """The segment where the line through a,b crosses the polygon boundary."""
    pts = []
    n = len(poly)
    for i in range(n):
        p, q = poly[i], poly[(i + 1) % n]
        sp, sq = _side(p, a, b), _side(q, a, b)
        if sp * sq < 0 and (sp - sq) != 0:
            t = sp / (sp - sq)
            pts.append([p[0] + (q[0] - p[0]) * t, p[1] + (q[1] - p[1]) * t])
    uniq = []
    for p in pts:
        if not any(abs(p[0] - u[0]) < 0.6 and abs(p[1] - u[1]) < 0.6 for u in uniq):
            uniq.append(p)
    return uniq


def _densify(points, step: float = 42.0):
    out = []
    for i in range(len(points) - 1):
        a, b = points[i], points[i + 1]
        distance = math.hypot(b[0] - a[0], b[1] - a[1])
        count = max(1, int(distance / step))
        for k in range(count):
            t = k / count
            out.append([a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t])
    out.append(list(points[-1]))
    return out


def _warp_xy(x, y, width, height, phase):
    """A smooth, deterministic distortion that curves straight streets."""
    u, v = x / width, y / height
    return (x + 18 * math.sin(math.tau * v * 1.6 + phase) + 9 * math.sin(math.tau * v * 3.3 + phase * 1.7),
            y + 16 * math.sin(math.tau * u * 1.5 + phase * 1.3) + 8 * math.sin(math.tau * u * 3.1 + phase * 0.7))


def _warp_path(points, width, height, phase):
    return [[round(wx, 1), round(wy, 1)] for wx, wy in
            (_warp_xy(x, y, width, height, phase) for x, y in _densify(points))]


def _warp_map(world_map: dict, width: int, height: int, phase: float) -> dict:
    """Bend the linear features (streets, roads, water, lines, places).

    Blocks / parks / compounds are generated already in warped space and stay
    rectangular, so they are not touched here.
    """
    for street in world_map.get("streets", []):
        street["points"] = _warp_path(street["points"], width, height, phase)
    for road in world_map.get("roads", []):
        road["points"] = _warp_path(road["points"], width, height, phase)
    for lake in world_map.get("lakes", []):
        lake["points"] = _warp_ring(lake["points"], width, height, phase)
        lake["label"] = list(_warp_xy(lake["label"][0], lake["label"][1], width, height, phase))
    for river in world_map.get("rivers", []):
        river["points"] = _warp_path(river["points"], width, height, phase)
    for district in world_map.get("districts", []):
        district["x"], district["y"] = (round(v, 1) for v in _warp_xy(district["x"], district["y"], width, height, phase))
    for loc in world_map.get("locations", []):
        loc["x"], loc["y"] = (round(v, 1) for v in _warp_xy(loc["x"], loc["y"], width, height, phase))
    for building in world_map.get("named_buildings", []):
        building["x"], building["y"] = (round(v, 1) for v in _warp_xy(building["x"], building["y"], width, height, phase))
    for line in world_map.get("metro", []) + world_map.get("bus", []):
        line["points"] = _warp_path(line["points"], width, height, phase)
        for stop in line.get("stations", []):
            stop["x"], stop["y"] = (round(v, 1) for v in _warp_xy(stop["x"], stop["y"], width, height, phase))
        line["stops"] = line.get("stations", [])
    return world_map


def _warp_ring(points, width, height, phase):
    dense = []
    n = len(points)
    for i in range(n):
        a, b = points[i], points[(i + 1) % n]
        dense.append(a)
        dense.append([(a[0] + b[0]) / 2, (a[1] + b[1]) / 2])
    return [[round(wx, 1), round(wy, 1)] for wx, wy in
            (_warp_xy(x, y, width, height, phase) for x, y in dense)]


def _subdivide(poly, depth, rng, streets, arterials, max_depth, top_levels, min_area):
    if depth <= 0 or len(poly) < 3 or _area(poly) < min_area:
        return [poly]
    minx = min(p[0] for p in poly); maxx = max(p[0] for p in poly)
    miny = min(p[1] for p in poly); maxy = max(p[1] for p in poly)
    vertical = (maxx - minx) >= (maxy - miny)
    theta = (math.pi / 2 if vertical else 0.0) + rng.uniform(-0.4, 0.4)
    direction = [math.cos(theta), math.sin(theta)]
    normal = [-direction[1], direction[0]]
    center = _centroid(poly)
    span = (maxy - miny) if vertical else (maxx - minx)
    off = rng.uniform(-0.18, 0.18) * span
    point = [center[0] + normal[0] * off, center[1] + normal[1] * off]
    a = [point[0] - direction[0] * 1400, point[1] - direction[1] * 1400]
    b = [point[0] + direction[0] * 1400, point[1] + direction[1] * 1400]
    left = _clip(poly, a, b, True)
    right = _clip(poly, a, b, False)
    if len(left) < 3 or len(right) < 3:
        return [poly]
    seg = _cut(poly, a, b)
    if len(seg) >= 2:
        segment = [[round(seg[0][0], 1), round(seg[0][1], 1)], [round(seg[1][0], 1), round(seg[1][1], 1)]]
        kind = "highway" if depth >= max_depth - 1 else ("arterial" if depth >= max_depth - 3 else "street")
        streets.append({"points": segment, "kind": kind})
        if kind != "street":
            arterials.append(segment)
    args = (depth - 1, rng, streets, arterials, max_depth, top_levels, min_area)
    return _subdivide(left, *args) + _subdivide(right, *args)


# ----------------------------------------------------------------- assets/naming
def _blob(cx, cy, radius, rng, name="湖"):
    points = []
    phase = rng.uniform(0, math.tau)
    for index in range(18):
        angle = math.tau * index / 18
        r = radius * (0.78 + 0.32 * math.sin(3 * angle + phase) + 0.12 * math.sin(5 * angle + phase * 2))
        points.append([round(cx + math.cos(angle) * r, 1), round(cy + math.sin(angle) * r, 1)])
    return {"name": name, "points": points, "label": [round(cx, 1), round(cy, 1)], "r": round(radius, 1)}


def _river(rng, width, height):
    start_x = rng.choice([width * 0.08, width * 0.92])
    start_y = rng.uniform(height * 0.1, height * 0.35) if start_x < width / 2 else rng.uniform(height * 0.65, height * 0.9)
    points = []
    for step in [i / 8 for i in range(9)]:
        x = start_x + (width - 2 * start_x) * step + math.sin(step * math.tau) * width * 0.06
        y = start_y + (height - 2 * start_y) * step + math.cos(step * math.tau) * height * 0.05
        points.append([round(x, 1), round(y, 1)])
    return {"name": "河", "points": points}


def _norm_points(pts, width, height):
    if not isinstance(pts, list) or len(pts) < 2:
        return None
    out = [[round(_clamp(_float(p[0], width / 2), 0, width), 1), round(_clamp(_float(p[1], height / 2), 0, height), 1)]
           for p in pts if isinstance(p, (list, tuple)) and len(p) >= 2]
    return out if len(out) >= 2 else None


def _resolve(ref, index):
    if isinstance(ref, dict):
        if ref.get("x") is not None:
            return (_float(ref.get("x"), 0.0), _float(ref.get("y"), 0.0))
        ref = ref.get("at") or ref.get("place") or ref.get("name")
    if isinstance(ref, str):
        return index.get(ref.strip())
    return None


def _norm_lakes(water, rng, width, height):
    lakes = []
    for entry in (water or []):
        if isinstance(entry, dict) and entry.get("kind") != "river" and entry.get("x") is not None:
            lakes.append(_blob(_clamp(_float(entry.get("x"), width / 2), 80, width - 80),
                               _clamp(_float(entry.get("y"), height / 2), 80, height - 80),
                               _clamp(_float(entry.get("r"), 80), 40, 150), rng,
                               str(entry.get("name") or "湖")[:12]))
    if not lakes:
        lakes.append(_blob(rng.uniform(width * 0.58, width * 0.8), rng.uniform(height * 0.6, height * 0.8), rng.uniform(60, 90), rng))
    return lakes


def _norm_rivers(water, rng, width, height):
    rivers = []
    for entry in (water or []):
        if isinstance(entry, dict) and entry.get("kind") == "river":
            pts = _norm_points(entry.get("points"), width, height)
            if pts:
                rivers.append({"name": str(entry.get("name") or "河")[:12], "points": pts})
    if not rivers:
        rivers.append(_river(rng, width, height))
    return rivers


def _norm_districts(raw, names, width, height):
    out = []
    if isinstance(raw, list):
        for entry in raw[:8]:
            if not isinstance(entry, dict):
                continue
            name = str(entry.get("name") or "").strip()
            if not name:
                continue
            out.append({"name": name[:16],
                        "x": round(_clamp(_float(entry.get("x"), width / 2), 70, width - 70), 1),
                        "y": round(_clamp(_float(entry.get("y"), height / 2), 70, height - 70), 1),
                        "r": round(_clamp(_float(entry.get("r"), 220), 140, 340), 1)})
    if not out:
        pool = [str(n) for n in (names or []) if str(n).strip()] or _DEFAULT_DISTRICTS
        count = min(6, len(pool))
        for index in range(count):
            angle = -math.pi / 2 + math.tau * index / count
            out.append({"name": pool[index][:16],
                        "x": round(width / 2 + math.cos(angle) * width * 0.28, 1),
                        "y": round(height / 2 + math.sin(angle) * height * 0.28, 1),
                        "r": round(min(width, height) * 0.24, 1)})
    return out


def _route_through(waypoints, rng):
    if len(waypoints) < 2:
        return waypoints
    points = [waypoints[0]]
    for a, b in zip(waypoints, waypoints[1:]):
        points.append([round((a[0] + b[0]) / 2 + rng.uniform(-24, 24), 1),
                       round((a[1] + b[1]) / 2 + rng.uniform(-24, 24), 1)])
        points.append([round(b[0], 1), round(b[1], 1)])
    return points


def _norm_roads(raw, index, width, height, rng):
    out = []
    for entry in (raw or [])[:20]:
        if isinstance(entry, str):
            entry = {"name": entry}
        if not isinstance(entry, dict):
            continue
        name = str(entry.get("name") or "").strip()[:20]
        kind = str(entry.get("kind") or "arterial").strip().lower()
        if kind not in _ROAD_KINDS:
            kind = "arterial"
        path = _norm_points(entry.get("points"), width, height)
        if not path:
            a = _resolve(entry.get("from"), index)
            b = _resolve(entry.get("to"), index)
            if a and b:
                path = _route_through([[a[0], a[1]], [b[0], b[1]]], rng)
        if path:
            out.append({"name": name, "kind": kind, "points": path})
    return out


def _norm_transit(raw, index, width, height, rng, colors, fallback_names, network=None):
    out = []
    for i, line in enumerate((raw or [])[:8]):
        if not isinstance(line, dict):
            continue
        name = str(line.get("name") or (fallback_names[i] if i < len(fallback_names) else f"线路{i + 1}"))[:20]
        stops = []
        for entry in (line.get("stations") or line.get("stops") or [])[:16]:
            label, point = "", None
            if isinstance(entry, str):
                label, point = entry.strip(), index.get(entry.strip())
            elif isinstance(entry, dict):
                label = str(entry.get("name") or "").strip()
                point = _resolve(entry, index)
            if point:
                stops.append({"name": label[:16], "x": round(_clamp(point[0], 0, width), 1), "y": round(_clamp(point[1], 0, height), 1)})
        stops = _dedupe(stops, lambda s: s["name"] or f"{s['x']},{s['y']}")
        if len(stops) < 2:
            continue
        points = _route_along_streets(stops, network) if network else _route_through([[s["x"], s["y"]] for s in stops], rng)
        # The colour ends up in an inline style on the panel, so only accept a
        # literal hex value; anything else (model-provided) falls back.
        color = str(line.get("color") or "").strip()
        if not _COLOR_RE.match(color):
            color = colors[i % len(colors)]
        out.append({"name": name, "color": color,
                    "points": points, "stations": stops, "stops": stops})
    return _dedupe(out, lambda line: line["name"])


def _norm_parks(raw, width, height):
    out = []
    for entry in (raw or [])[:6]:
        if isinstance(entry, str):
            entry = {"name": entry}
        if not isinstance(entry, dict):
            continue
        name = str(entry.get("name") or "公园")[:16]
        pts = _norm_points(entry.get("points"), width, height)
        if not pts and entry.get("x") is not None:
            cx = _clamp(_float(entry.get("x"), width / 2), 60, width - 60)
            cy = _clamp(_float(entry.get("y"), height / 2), 60, height - 60)
            r = _clamp(_float(entry.get("r"), 70), 40, 130)
            pts = [[round(cx + math.cos(math.tau * k / 8) * r, 1), round(cy + math.sin(math.tau * k / 8) * r * 0.8, 1)] for k in range(8)]
        if pts and len(pts) >= 3:
            out.append({"name": name, "points": pts, "trees": []})
    return out


def _building_name(rng, used):
    for _ in range(60):
        name = rng.choice(_BUILDING_PREFIX) + rng.choice(_BUILDING_SUFFIX)
        if name not in used:
            used.add(name)
            return name
    return ""


def _compound_names(count, rng):
    names, seen = [], set()
    guard = 0
    while len(names) < count and guard < count * 20:
        guard += 1
        name = rng.choice(_BUILDING_PREFIX) + rng.choice(_COMPOUND_SUFFIX)
        if name not in seen:
            seen.add(name)
            names.append(name)
    while len(names) < count:
        names.append(f"{len(names) + 1}号小区")
    return names


def _rects_from_poly(warped_poly, rng):
    """Regular (axis-aligned) building footprints inside a block's bounds."""
    xs = [p[0] for p in warped_poly]
    ys = [p[1] for p in warped_poly]
    minx, maxx, miny, maxy = min(xs), max(xs), min(ys), max(ys)
    width, height = maxx - minx, maxy - miny
    if width < 16 or height < 16:
        return []
    nx = 1 if width < 52 else rng.choice([1, 2])
    ny = 1 if height < 52 else rng.choice([1, 2])
    margin, gap = 6.0, 5.0
    rects = []
    for gx in range(nx):
        for gy in range(ny):
            x0 = minx + margin + (width - 2 * margin) * gx / nx + gap / 2
            x1 = minx + margin + (width - 2 * margin) * (gx + 1) / nx - gap / 2
            y0 = miny + margin + (height - 2 * margin) * gy / ny + gap / 2
            y1 = miny + margin + (height - 2 * margin) * (gy + 1) / ny - gap / 2
            if x1 - x0 < 7 or y1 - y0 < 7:
                continue
            rects.append([[round(x0, 1), round(y0, 1)], [round(x1, 1), round(y0, 1)],
                          [round(x1, 1), round(y1, 1)], [round(x0, 1), round(y1, 1)]])
    return rects


def _norm_compounds(raw, names, width, height):
    out = []
    if isinstance(raw, list):
        for entry in raw[:8]:
            if isinstance(entry, str):
                entry = {"name": entry}
            if not isinstance(entry, dict):
                continue
            name = str(entry.get("name") or "").strip()
            if not name:
                continue
            out.append({"name": name[:16],
                        "x": round(_clamp(_float(entry.get("x"), width / 2), 60, width - 60), 1),
                        "y": round(_clamp(_float(entry.get("y"), height / 2), 60, height - 60), 1),
                        "r": round(_clamp(_float(entry.get("r"), 110), 60, 200), 1)})
    return out


def _road_names(count, rng):
    names, seen, guard = [], set(), 0
    while len(names) < count and guard < count * 40:
        guard += 1
        name = rng.choice(_ROAD_PREFIX) + rng.choice(_ROAD_SUFFIX)
        if name not in seen:
            seen.add(name)
            names.append(name)
    while len(names) < count:
        names.append(f"第{len(names) + 1}大街")
    return names


def _dist_point_segment(px, py, ax, ay, bx, by) -> float:
    dx, dy = bx - ax, by - ay
    if dx == 0 and dy == 0:
        return math.hypot(px - ax, py - ay)
    t = max(0.0, min(1.0, ((px - ax) * dx + (py - ay) * dy) / (dx * dx + dy * dy)))
    return math.hypot(px - (ax + dx * t), py - (ay + dy * t))


def _in_water(x, y, lakes, rivers, margin: float = 32.0) -> bool:
    """True if (x,y) is on a lake or within a river's channel."""
    for lake in lakes:
        lx, ly = lake["label"]
        if math.hypot(x - lx, y - ly) < lake.get("r", 80) * 0.9:
            return True
    for river in rivers:
        points = river["points"]
        for i in range(len(points) - 1):
            if _dist_point_segment(x, y, points[i][0], points[i][1], points[i + 1][0], points[i + 1][1]) < margin:
                return True
    return False


def _convex_hull(points):
    """Andrew's monotone chain — an organic outline for a compound."""
    pts = sorted({(round(p[0], 2), round(p[1], 2)) for p in points})
    if len(pts) < 3:
        return [list(p) for p in pts]

    def cross(o, a, b):
        return (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0])

    lower = []
    for p in pts:
        while len(lower) >= 2 and cross(lower[-2], lower[-1], p) <= 0:
            lower.pop()
        lower.append(p)
    upper = []
    for p in reversed(pts):
        while len(upper) >= 2 and cross(upper[-2], upper[-1], p) <= 0:
            upper.pop()
        upper.append(p)
    return [list(p) for p in (lower[:-1] + upper[:-1])]


def _dedupe(items, key):
    seen, out = set(), []
    for item in items:
        value = key(item)
        if value and value in seen:
            continue
        if value:
            seen.add(value)
        out.append(item)
    return out


def _split_into(poly, count, rng):
    """Split a polygon into ~count organic pieces by recursive bisection."""
    pieces = [poly]
    guard = 0
    while len(pieces) < count and guard < count * 4:
        guard += 1
        index = max(range(len(pieces)), key=lambda k: _area(pieces[k]))
        target = pieces[index]
        minx = min(p[0] for p in target); maxx = max(p[0] for p in target)
        miny = min(p[1] for p in target); maxy = max(p[1] for p in target)
        vertical = (maxx - minx) >= (maxy - miny)
        theta = (math.pi / 2 if vertical else 0.0) + rng.uniform(-0.5, 0.5)
        direction = [math.cos(theta), math.sin(theta)]
        normal = [-direction[1], direction[0]]
        center = _centroid(target)
        span = (maxy - miny) if vertical else (maxx - minx)
        off = rng.uniform(-0.16, 0.16) * span
        point = [center[0] + normal[0] * off, center[1] + normal[1] * off]
        a = [point[0] - direction[0] * 1400, point[1] - direction[1] * 1400]
        b = [point[0] + direction[0] * 1400, point[1] + direction[1] * 1400]
        left = _clip(target, a, b, True)
        right = _clip(target, a, b, False)
        if len(left) < 3 or len(right) < 3:
            break
        pieces[index:index + 1] = [left, right]
    return pieces


def _route_along_streets(stations, streets):
    """Follow the street network between stations instead of drawing rulers."""
    nodes: dict = {}
    adjacency: dict = {}

    def node_id(x, y):
        key = (int(round(x / 7)), int(round(y / 7)))
        nodes.setdefault(key, [x, y])
        return key

    for segment in streets:
        points = segment.get("points", [])
        for i in range(len(points) - 1):
            a = node_id(points[i][0], points[i][1])
            b = node_id(points[i + 1][0], points[i + 1][1])
            if a == b:
                continue
            adjacency.setdefault(a, set()).add(b)
            adjacency.setdefault(b, set()).add(a)
    if not nodes:
        return [[round(s["x"], 1), round(s["y"], 1)] for s in stations]

    def nearest(x, y):
        return min(nodes, key=lambda k: (nodes[k][0] - x) ** 2 + (nodes[k][1] - y) ** 2)

    def path_between(s, t):
        from collections import deque
        queue = deque([s])
        previous = {s: None}
        while queue:
            current = queue.popleft()
            if current == t:
                break
            for neighbor in adjacency.get(current, ()):
                if neighbor not in previous:
                    previous[neighbor] = current
                    queue.append(neighbor)
        if t not in previous:
            return None
        path, cursor = [], t
        while cursor is not None:
            path.append(nodes[cursor])
            cursor = previous[cursor]
        path.reverse()
        return path

    routed = []
    for index, station in enumerate(stations):
        if index == 0:
            routed.append([round(station["x"], 1), round(station["y"], 1)])
            continue
        previous = stations[index - 1]
        path = path_between(nearest(previous["x"], previous["y"]), nearest(station["x"], station["y"]))
        if path:
            routed.extend([[round(x, 1), round(y, 1)] for x, y in path])
        routed.append([round(station["x"], 1), round(station["y"], 1)])
    return routed


def _fallback_metro(width, height, network=None):
    """A small network: several east-west / north-south / diagonal lines."""
    lines = []

    def add(index, stations):
        points = _route_along_streets(stations, network) if network else [[s["x"], s["y"]] for s in stations]
        lines.append({"name": f"地铁{index + 1}号线", "color": _METRO_COLORS[index % len(_METRO_COLORS)],
                      "points": points, "stations": stations, "stops": stations})

    index = 0
    for frac, count in ((0.20, 12), (0.40, 14), (0.60, 14), (0.80, 12)):
        y = height * frac
        add(index, [{"name": f"站{k + 1}", "x": round(60 + (width - 120) * k / (count - 1), 1), "y": round(y, 1)}
                    for k in range(count)])
        index += 1
    for frac, count in ((0.24, 11), (0.5, 11), (0.76, 11)):
        x = width * frac
        add(index, [{"name": f"站{k + 1}", "x": round(x, 1), "y": round(60 + (height - 120) * k / (count - 1), 1)}
                    for k in range(count)])
        index += 1
    add(index, [{"name": f"站{k + 1}", "x": round(90 + (width - 180) * k / 9, 1),
                 "y": round(80 + (height - 160) * k / 9, 1)} for k in range(10)])
    return lines


def _fallback_bus(index, network=None):
    names = list(index.keys())
    if len(names) < 2:
        return []
    routes = []
    for r, start in enumerate((0, 1, 2)):
        rotated = names[start:] + names[:start]
        stops = [{"name": n, "x": round(index[n][0], 1), "y": round(index[n][1], 1)} for n in rotated[:8]]
        if len(stops) < 2:
            continue
        points = _route_along_streets(stops, network) if network else [[s["x"], s["y"]] for s in stops]
        routes.append({"name": f"公交{11 + r}路", "color": _BUS_COLORS[r % len(_BUS_COLORS)],
                       "points": points, "stations": stops, "stops": stops})
    return routes


def _landmass(seed, width, height, vertices: int = 96):
    rng = random.Random(seed)
    harmonics = [(rng.uniform(0.05, 0.12), rng.choice([2, 3, 4, 5]), rng.uniform(0, math.tau)) for _ in range(4)]
    cx, cy = width / 2, height / 2
    points = []
    for index in range(vertices):
        angle = math.tau * index / vertices
        radius = 1.0 + sum(amp * math.sin(freq * angle + phase) for amp, freq, phase in harmonics)
        points.append([round(cx + math.cos(angle) * width * 0.40 * radius, 1),
                       round(cy + math.sin(angle) * height * 0.40 * radius, 1)])
    return points, (cx, cy)


def build_nation(*, country, city, provinces, cities, width=WIDTH, height=HEIGHT):
    """A nationwide overview: the land, its provinces and cities, and the roads
    between them. Deterministic per country/city."""
    seed = _seed(f"nation|{country}|{city}")
    rng = random.Random(seed)
    land, center = _landmass(seed, width, height)
    names = [str(p).strip() for p in (provinces or []) if str(p).strip()]
    if not names:
        names = [p + "省" for p in rng.sample(_BUILDING_PREFIX, 6)]
    count = max(3, min(len(names), 8))
    province_shapes = []
    for k, piece in enumerate(_split_into(land, count, rng)):
        name = names[k] if k < len(names) else f"{country}{k + 1}省"
        province_shapes.append({"name": str(name)[:16],
                                "points": [[round(p[0], 1), round(p[1], 1)] for p in piece],
                                "label": _centroid(piece)})
    province_shapes = _dedupe(province_shapes, lambda p: p["name"])

    city_defs = []
    if isinstance(cities, list):
        for entry in cities[:12]:
            if isinstance(entry, dict) and entry.get("name"):
                city_defs.append({"name": str(entry["name"])[:16],
                                  "x": round(_clamp(_float(entry.get("x"), center[0]), 40, width - 40), 1),
                                  "y": round(_clamp(_float(entry.get("y"), center[1]), 40, height - 40), 1),
                                  "capital": bool(entry.get("capital"))})
    city_defs = _dedupe(city_defs, lambda c: c["name"])
    if not city_defs:
        city_defs.append({"name": (city or "首府")[:16], "x": round(center[0], 1), "y": round(center[1], 1), "capital": True})
        for prov in province_shapes:
            city_defs.append({"name": prov["name"].replace("省", "")[:16],
                              "x": prov["label"][0], "y": prov["label"][1], "capital": False})
    if city_defs and not any(c["capital"] for c in city_defs):
        city_defs[0]["capital"] = True

    capital = next((c for c in city_defs if c["capital"]), city_defs[0] if city_defs else None)
    routes = []
    if capital:
        for c in city_defs:
            if c is capital:
                continue
            routes.append({"points": [[capital["x"], capital["y"]],
                                      [round((capital["x"] + c["x"]) / 2 + rng.uniform(-24, 24), 1),
                                       round((capital["y"] + c["y"]) / 2 + rng.uniform(-24, 24), 1)],
                                      [c["x"], c["y"]]]})
    return {"kind": "nation", "title": (country or city or "全国") + "地图",
            "width": width, "height": height, "country": country, "city": city,
            "land": land, "provinces": province_shapes, "cities": city_defs, "routes": routes}


def _location_edges(locations) -> list[list[str]]:
    """Connect the story's places into a walkable graph (nearest-unvisited chain),
    so the runtime can move actors between them regardless of map kind."""
    ids = [loc["id"] for loc in locations if loc.get("id")]
    if len(ids) < 2:
        return []
    position = {loc["id"]: (loc["x"], loc["y"]) for loc in locations if loc.get("id")}
    edges: list[list[str]] = []
    current = ids[0]
    remaining = set(ids[1:])
    while remaining:
        nxt = min(remaining, key=lambda i: (position[i][0] - position[current][0]) ** 2
                  + (position[i][1] - position[current][1]) ** 2)
        edges.append([current, nxt])
        remaining.discard(nxt)
        current = nxt
    return edges


def build_city(*, country, city, districts, water, roads, metro, bus, parks, compounds, buildings,
               names, locations, actors, title, width=WIDTH, height=HEIGHT):
    seed = _seed(f"{country}|{city}")
    rng = random.Random(seed)
    phase = (seed % 628) / 100.0
    margin = 60

    lakes = _norm_lakes(water, rng, width, height)
    rivers = _norm_rivers(water, rng, width, height)

    placed = []
    for loc in locations:
        placed.append({**loc,
                       "x": round(_clamp(_float(loc.get("x"), width / 2), 60, width - 60), 1),
                       "y": round(_clamp(_float(loc.get("y"), height / 2), 60, height - 60), 1),
                       "lat": None, "lng": None})
    index = {loc["name"]: (loc["x"], loc["y"]) for loc in placed if loc.get("name")}

    def warp(x, y):
        return _warp_xy(x, y, width, height, phase)

    def wpoly(poly):
        dense = []
        n = len(poly)
        for i in range(n):
            a, b = poly[i], poly[(i + 1) % n]
            dense.append(a)
            dense.append([(a[0] + b[0]) / 2, (a[1] + b[1]) / 2])
        return [list(warp(x, y)) for x, y in dense]

    warped_rivers = [{"points": _warp_path(rv["points"], width, height, phase)} for rv in rivers]
    warped_lakes = [{"label": list(warp(lk["label"][0], lk["label"][1])), "r": lk.get("r", 80)} for lk in lakes]

    # --- road network: recursive subdivision --------------------------------
    root = [[margin, margin], [width - margin, margin], [width - margin, height - margin], [margin, height - margin]]
    streets: list[dict] = []
    arterials: list[list] = []
    leaves = _subdivide(root, 6, rng, streets, arterials, max_depth=6, top_levels=2, min_area=_MIN_BLOCK_AREA)
    ring = [[width / 2 + math.cos(math.tau * k / 60) * width * 0.33,
             height / 2 + math.sin(math.tau * k / 60) * height * 0.33] for k in range(60)]
    streets.append({"points": ring, "kind": "highway"})
    street_only = [seg for seg in streets if seg.get("kind") == "street"]
    majors = [seg for seg in streets if seg.get("kind") != "street"]
    major_names = _road_names(len(majors), rng)
    generated_roads = [{"name": major_names[i], "kind": seg.get("kind", "arterial"), "points": seg["points"]}
                       for i, seg in enumerate(majors)]

    # --- compounds (小区) ----------------------------------------------------
    compound_defs = _norm_compounds(compounds, names, width, height)
    if not compound_defs:
        for i in range(5):
            angle = -math.pi / 2 + math.tau * i / 5
            compound_defs.append({"name": "", "x": width / 2 + math.cos(angle) * width * 0.27,
                                  "y": height / 2 + math.sin(angle) * height * 0.28, "r": 140})
    compound_names = _compound_names(len(compound_defs), rng)
    for i, entry in enumerate(compound_defs):
        if not entry.get("name"):
            entry["name"] = compound_names[i]
    compound_defs = _dedupe(compound_defs, lambda d: d["name"])

    def nearest_compound(cx, cy):
        return min(range(len(compound_defs)),
                   key=lambda i: (compound_defs[i]["x"] - cx) ** 2 + (compound_defs[i]["y"] - cy) ** 2)

    blocks: list[dict] = []
    park_shapes: list[dict] = []
    member_points = [[] for _ in compound_defs]
    used_names: set = set()
    park_pick = set(rng.sample(range(len(leaves)), min(max(6, len(leaves) // 7), len(leaves)))) if leaves else set()
    for idx, leaf in enumerate(leaves):
        wleaf = wpoly(leaf)
        cx, cy = _centroid(wleaf)
        if _in_water(cx, cy, warped_lakes, warped_rivers):
            continue
        member_points[nearest_compound(cx, cy)].extend(wleaf)
        if idx in park_pick:
            park_shapes.append({"name": "公园", "points": [[round(p[0], 1), round(p[1], 1)] for p in wleaf],
                                "trees": [[round(cx + rng.uniform(-18, 18), 1), round(cy + rng.uniform(-16, 16), 1)] for _ in range(4)]})
            continue
        for rect in _rects_from_poly(wleaf, rng):
            tower = rng.random() < 0.16
            name = _building_name(rng, used_names) if (tower or rng.random() < 0.14) else ""
            blocks.append({"points": rect, "shade": rng.randint(0, 3), "tower": tower, "name": name})

    compounds_out = []
    for i, entry in enumerate(compound_defs):
        hull = _convex_hull(member_points[i]) if member_points[i] else []
        if len(hull) < 3:
            continue
        compounds_out.append({"name": entry["name"],
                              "points": [[round(x, 1), round(y, 1)] for x, y in hull]})

    # model-named landmark buildings (from the setting), if any
    named_buildings = []
    for entry in (buildings or [])[:20]:
        if isinstance(entry, dict) and entry.get("name"):
            named_buildings.append({"name": str(entry["name"])[:24],
                                    "x": round(_clamp(_float(entry.get("x"), width / 2), 40, width - 40), 1),
                                    "y": round(_clamp(_float(entry.get("y"), height / 2), 40, height - 40), 1)})
    named_buildings = _dedupe(named_buildings, lambda b: b["name"])

    model_roads = _norm_roads(roads, index, width, height, rng)
    roads_out = _dedupe(model_roads or generated_roads, lambda r: r["name"])
    metro_out = _norm_transit(metro, index, width, height, rng, _METRO_COLORS, ["地铁1号线", "地铁2号线"], network=streets) or _fallback_metro(width, height, streets)
    bus_out = _norm_transit(bus, index, width, height, rng, _BUS_COLORS, ["公交1路", "公交2路"], network=streets) or _fallback_bus(index, streets)
    parks_out = _dedupe(_norm_parks(parks, width, height) or park_shapes, lambda p: p["name"])

    world_map = {
        "kind": "fictional",
        "title": title or (city or country or "世界") + "地图",
        "width": width, "height": height, "country": country, "city": city,
        "streets": street_only, "roads": roads_out,
        "blocks": blocks, "parks": parks_out, "compounds": compounds_out,
        "named_buildings": named_buildings,
        "water": list(water or []), "lakes": lakes, "rivers": rivers,
        "districts": _norm_districts(districts, names, width, height),
        "metro": metro_out, "bus": bus_out,
        "locations": placed, "actors": list(actors), "edges": _location_edges(placed),
    }
    return _warp_map(world_map, width, height, phase)
